[package]
name = "plugin-backstage-catalog"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
basalt-plugin-sdk = { path = "../basalt-plugin-sdk" }
serde_json = "1"
serde_yaml = "0.9"
serde = { version = "1", features = ["derive"] }

[profile.release]
opt-level = "s"
lto = true
strip = true
codegen-units = 1
